# Default values for webapp chart
deploymentName: webapp
namespace: default
replicaCount: 1
environment: production
# Image configuration
image:
  repository: 990060748279.dkr.ecr.us-east-1.amazonaws.com/swapp-dev
  tag: latest
  pullPolicy: Always
# Service configuration
service:
  type: ClusterIP
  port: 80
# Ingress configuration
ingress:
  enabled: true
  hostnames:
    - webapp.local
  path: /
