apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    server {
      listen 80;
      root /usr/share/nginx/html;
      index index.html index.htm;
      
      # Health checks - simplified
      location = / {
        return 200;
      }
      
      # All other paths
      location / {
        try_files $uri $uri/ /index.html;
      }
    }
