apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    server {
      listen 80;
      root /usr/share/nginx/html;
      
      # Root path redirect to app path if configured
      location = / {
        {{- if .Values.ingress.addRootPath }}
        try_files $uri $uri/ /webapp-dev/index.html;
        {{- else }}
        try_files $uri $uri/ /index.html;
        {{- end }}
      }
      
      # Handle the webapp-dev path
      location /webapp-dev {
        alias /usr/share/nginx/html/webapp-dev;
        try_files $uri $uri/ /webapp-dev/index.html;
        # Enable directory listing for debugging
        autoindex on;
      }

      # Handle asset files with proper headers
      location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, max-age=31536000";
        try_files $uri /webapp-dev$uri =404;
      }
    }