apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    server {
      listen 80;
      root /usr/share/nginx/html;
      index index.html index.htm;
      
      location / {
        try_files $uri $uri/ /index.html;
      }
      
      # Handle all paths to make SPA routing work
      location ~ ^/webapp-prod(/|$)(.*) {
        try_files $uri $uri/ /index.html;
      }
    }