apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    server {
      listen 80;
      root /usr/share/nginx/html;
      index index.html index.htm;
      
      # Root location block for direct root access
      location / {
        try_files $uri $uri/ /index.html;
      }
      
      # Specific block for /webapp-prod path - simplified for reliability
      location /webapp-prod {
        alias /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
        index index.html index.htm;
      }
      
      # Handle any sub-paths under /webapp-prod
      location ~ ^/webapp-prod/(.*)$ {
        alias /usr/share/nginx/html/$1;
        try_files $uri $uri/ /index.html;
        index index.html index.htm;
      }
    }