apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    server {
      listen 80;
      root /usr/share/nginx/html;
      
      # Handle requests to /webapp-prod
      location /webapp-prod {
        alias /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
      }
      
      # Handle static assets
      location /assets/ {
        alias /usr/share/nginx/html/assets/;
        try_files $uri =404;
      }
      
      # Rewrite /webapp-prod/assets to /assets
      location /webapp-prod/assets/ {
        alias /usr/share/nginx/html/assets/;
      }
      
      # Default location
      location / {
        try_files $uri $uri/ /index.html;
      }
    }