apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    server {
      listen 80;
      root /usr/share/nginx/html;
      
      location {{ .Values.ingress.path | default "/" }} {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ {{ .Values.ingress.path | default "/" }}/index.html;
      }
      
      location / {
        try_files $uri $uri/ /index.html;
      }
    }
volumeMounts:
- name: nginx-config
  mountPath: /etc/nginx/conf.d/default.conf
  subPath: nginx.conf
volumes:
- name: nginx-config
  configMap:
    name: {{ .Release.Name }}-nginx-config