apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    server {
      listen 80;
      root /usr/share/nginx/html;
      index index.html index.htm;
      
      # Added to help with troubleshooting
      error_log /var/log/nginx/error.log debug;
      
      # Root location block - make this the default for all
      location / {
        try_files $uri $uri/ /index.html;
      }
      
      # More permissive block for webapp-prod
      location ^~ /webapp-prod {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
        # Added debug headers
        add_header X-Debug-Path $uri;
        add_header X-Debug-Host $host;
      }
    }