apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    server {
      listen 80;
      root /usr/share/nginx/html;
      index index.html index.htm;
      
      # Added to help with troubleshooting
      error_log /var/log/nginx/error.log debug;
      access_log /var/log/nginx/access.log;
      
      # Root location block
      location / {
        try_files $uri $uri/ /index.html;
      }
      
      # Handle webapp-prod path with alias instead of root
      location /webapp-prod/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /index.html;
        add_header X-Debug-Path $uri;
        add_header X-Debug-Host $host;
      }
    }