apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    server {
      listen 80;
      root /usr/share/nginx/html;
      index index.html index.htm;
      
      # Enable debug logging
      error_log /dev/stderr debug;
      
      # Simple path-based routing for standard web app
      location {{ .Values.ingress.path | default "/" }} {
        alias /usr/share/nginx/html/;
        index index.html index.htm;
        # Standard directory listing - no SPA handling
        autoindex on;
      }
      
      # Default location
      location / {
        index index.html index.htm;
      }
      
      # Handle static files with proper headers
      location ~* \.(jpg|jpeg|png|gif|ico|css|js)$ {
        expires 7d;
        add_header Cache-Control "public";
      }
    }