replicaCount: 2
resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 150m
    memory: 128Mi
ingress:
  hosts:
    - host: app.staging.example.com
      paths:
        - path: /
          pathType: Prefix
configMap:
  data:
    APP_ENV: staging
