apiVersion: v2
name: web-application
description: A Helm chart for deploying web applications with standardized configuration
type: application
version: 0.1.0
appVersion: "1.0.0"

- name: Create S3 bucket if it doesn't exist
  run: |
    if ! aws s3 ls "s3://my-helm-charts" 2>&1 | grep -q 'NoSuchBucket'; then
      echo "Bucket exists"
    else
      echo "Creating bucket"
      aws s3api create-bucket --bucket my-helm-charts --region us-east-1
    fi

- name: Upload chart to S3
  run: |
    aws s3 cp ./chart-packages/ s3://my-helm-charts/ --recursive
