replicaCount: 3
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
ingress:
  hosts:
    - host: app.production.example.com
      paths:
        - path: /
          pathType: Prefix
configMap:
  data:
    APP_ENV: production
