apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Kishorebskr/SW-dep.git'
    targetRevision: HEAD
    path: charts/webapp
    helm:
      valueFiles:
        - values/prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncWindow:
      schedule: 'Every 5 minutes'
      duration: 1h
