deploymentName: my-web-app
namespace: default
port: 80
replicaCount: 1
image:
  # FIX: Removed the ":latest" tag from the repository path
  repository: 990060748279.dkr.ecr.us-east-1.amazonaws.com/swapp-dev
  pullPolicy: IfNotPresent
  # This tag is a default and will be overridden by environment-specific values

  tag: "latest"
service:
  name: http
  type: LoadBalancer
  port: 80
  targetPort: 80
# Ingress is disabled by default.

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
resources: {}
serviceAccount:
  create: true
  annotations: {}
  name: ""
app:
  name: my-web-app
