deploymentName: my-web-app
namespace: default
port: 8080
replicaCount: 1
image:
  repository: nginxdemos/hello
  pullPolicy: IfNotPresent
  tag: "latest"
service:
  name: http
  type: ClusterIP
  port: 80
  targetPort: 80
ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - host: "" # Keep host empty for ALB to assign a DNS name
      paths:
        - path: /
          pathType: Prefix
