deploymentName: my-web-app
namespace: default
port: 8080
replicaCount: 1
image:
  repository: nginxdemos/hello
  pullPolicy: IfNotPresent
  tag: "latest"
service:
  name: http
  type: ClusterIP
  port: 80
  targetPort: 80
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
