deploymentName: webapp-prod
namespace: production
environment: production
port: 80
replicaCount: 2
image:
  repository: 222964728025.dkr.ecr.us-east-1.amazonaws.com/sw_ecr
  tag: prod
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
# Simple ingress config without domain

ingress:
  enabled: true
  className: nginx
  path: /webapp-prod
  annotations: {}
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"
# Remove these problematic environment variables

env:
  - name: PORT
    value: "80"
