deploymentName: webapp-prod
namespace: production
environment: production
port: 80
replicaCount: 2
image:
  repository: prakhar1989/flaskapp
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
# Simple ingress config without domain

ingress:
  enabled: true
  className: nginx
  path: /webapp-prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"
# Remove these problematic environment variables

env:
  - name: PORT
    value: "80"
