deploymentName: webapp-prod
namespace: production
port: 80
ingress:
  enabled: true
  hostnames:
    - webapp-prod.local
  path: /
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /