deploymentName: webapp-prod
namespace: production
environment: production
port: 80
replicaCount: 2
image:
  repository: 990060748279.dkr.ecr.us-east-1.amazonaws.com/swapp-dev
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
# Simple ingress config without domain
ingress:
  enabled: true
  className: nginx
  path: /webapp-prod # Unique path for production
  hostnames:
    - webapp.local
  annotations:
    # Don't rewrite - this often breaks React apps
    # nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"
env:
  - name: PUBLIC_URL
    value: "/webapp-prod"
  - name: REACT_APP_BASE_PATH
    value: "/webapp-prod"
