deploymentName: webapp-prod
namespace: production
port: 80
ingress:
  enabled: true
  hostnames:
    - webapp-prod.local
  path: /
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"
