name: Package Helm Chart

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.4

      - name: Package Helm Chart
        run: |
          helm package charts/webapp --destination ./charts/webapp/packages

      - name: Upload Helm Chart
        uses: actions/upload-artifact@v2
        with:
          name: webapp-chart
          path: charts/webapp/packages/*.tgz