apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sw-webapp-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/<your-user>/<your-repo>.git'
    targetRevision: main
    path: sw-webapp-chart
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sw-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
