name: Build and Publish

on:
  push:
    branches:
      - feature/01    # This restricts automatic triggers to this branch only
    paths:
      - 'helm/**'     # Still only triggers on changes to files in the helm directory
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.10.0'

    - name: Package Helm chart
      run: |
        mkdir -p ./chart-packages
        helm package ./helm/web-application -d ./chart-packages

    - name: Create S3 bucket if it doesn't exist
      run: |
        if ! aws s3 ls "s3://my-helm-charts" 2>&1 | grep -q 'NoSuchBucket'; then
          echo "Bucket exists"
        else
          echo "Creating bucket"
          aws s3api create-bucket --bucket my-helm-charts-wewewe --region us-east-1
        fi

    - name: Upload chart to S3
      run: |
        aws s3 cp ./chart-packages/ s3://my-helm-charts/ --recursive