name: GitOps Deploy SW WebApp
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (dev or prod)"
        required: true
        default: "dev"
      image_tag:
        description: "Docker image tag"
        required: true
        default: "latest"
jobs:
  update-values:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.44.1/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
      - name: Update values file
        run: |
          ENV_FILE=sw-webapp-chart/values-${{ github.event.inputs.environment }}.yaml
          yq eval ".image.tag = \"${{ github.event.inputs.image_tag }}\"" -i $ENV_FILE
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add $ENV_FILE
          git commit -m "Update ${{ github.event.inputs.environment }} image tag to ${{ github.event.inputs.image_tag }}"
          git push
